### 분석 목표 : 
1. 중점 관리 키워드, 저효율 키워드 추출 
2. 중점 관리 광고 그룹, 저효율 광고그룹 추출 

### 분석 과정 :
1. 데이터 전처리 
2. 데이터 탐색
3. 시각화
4. 데이터 분석

In [1]:
# 1. 데이터 전처리 
# - read_excel 함수를 사용하여 데이터 불러오기 
# - 데이터프레임 열단위 수치 연산 및 데이터 타입 다루기 
import pandas as pd
from pandas import DataFrame 
from pandas import Series

In [4]:
import matplotlib.pyplot as plt

In [8]:
import matplotlib
from matplotlib import font_manager, rc 
import platform

In [9]:
try : 
    if ploatform.system() == 'Windows' : 
        font_name = font_manager.FontProperties(fname="C:/Windows/Fonts/malgun.ttf").get_name()
        rc('font', family=font_name)
    else : 
        rc('font', family='AppleGothic')
except : 
    pass 
matplotlib.rcParams['axes.unicode_minus'] = False

In [14]:
# 운영체제 디렉토리 경로 구분자가 다름 
# - windows :  역슬래쉬(\)(|)
# - Mac : 슬래쉬(/)
df = pd.read_excel('./Data/네이버보고서.xls', skiprows=[0])
df

,광고그룹,키워드,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)"
0,올인원 패키지 : 디자인 툴_파워컨텐츠_포토샵,-,2319456,9606.0,0.414149,261.549448,2512444
1,올인원 패키지 : 업무자동화_VBA,-,767491,8058.0,1.049915,295.974808,2384965
2,ㅍAOP 전체_중복키워드_디자인(삭제),일러스트,1137840,324.0,0.028475,4841.663580,1568699
3,올인원 패키지 : 데이터 분석 입문 온라인_파콘,-,694106,1863.6,0.268489,630.593475,1175174
4,3. html,HTML,9626374,813.6,0.008452,1408.435349,1145903
...,...,...,...,...,...,...,...
1376,올인원 패키지 : 업무자동화_3. 엑셀,엑셀셀서식,24016,0.0,0.000000,0.000000,0
1377,올인원 패키지 : 업무자동화_3. 엑셀,MATCH,32287,0.0,0.000000,0.000000,0
1378,마케팅KPI수립,LTV,32602,0.0,0.000000,0.000000,0
1379,data_camp_rmp_8,DECISION,60844,0.0,0.000000,0.000000,0
1380,4. 웹의 동작,REST,61193,0.0,0.000000,0.000000,0

In [15]:
df = pd.read_excel('./Data/네이버보고서.xls', skiprows=[0])
df.head()

,광고그룹,키워드,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)"
0,올인원 패키지 : 디자인 툴_파워컨텐츠_포토샵,-,2319456,9606.0,0.414149,261.549448,2512444
1,올인원 패키지 : 업무자동화_VBA,-,767491,8058.0,1.049915,295.974808,2384965
2,ㅍAOP 전체_중복키워드_디자인(삭제),일러스트,1137840,324.0,0.028475,4841.663580,1568699
3,올인원 패키지 : 데이터 분석 입문 온라인_파콘,-,694106,1863.6,0.268489,630.593475,1175174
4,3. html,HTML,9626374,813.6,0.008452,1408.435349,1145903

In [25]:
df.isnull().sum()

광고그룹               0
키워드                0
노출수                0
클릭수                0
클릭률(%)             0
평균클릭비용(VAT포함,원)    0
총비용(VAT포함,원)       0
dtype: int64

In [18]:
df.isnull().sum(axis=1)

0       0
1       0
2       0
3       0
4       0
       ..
1376    0
1377    0
1378    0
1379    0
1380    0
Length: 1381, dtype: int64

### 데이터프레임의 열단위 수치연산 및 데이터 타입 다루기 
- 클릭수(반올림, 일의 자리로 변경) 
- 클릭률
- 평균 클릭 비용(VAT 포함, 원)

In [20]:
# 클릭수 : 한 번의 클릭이 총 몇 번 이루어졌는지 나타내는 지표 => 반올림 
clk = round(df['클릭수'], 0)

In [21]:
clk.astype(int)

0       9606
1       8058
2        324
3       1864
4        814
        ...
1376       0
1377       0
1378       0
1379       0
1380       0
Name: 클릭수, Length: 1381, dtype: int32

In [22]:
df.head()

,광고그룹,키워드,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)"
0,올인원 패키지 : 디자인 툴_파워컨텐츠_포토샵,-,2319456,9606.0,0.414149,261.549448,2512444
1,올인원 패키지 : 업무자동화_VBA,-,767491,8058.0,1.049915,295.974808,2384965
2,ㅍAOP 전체_중복키워드_디자인(삭제),일러스트,1137840,324.0,0.028475,4841.663580,1568699
3,올인원 패키지 : 데이터 분석 입문 온라인_파콘,-,694106,1863.6,0.268489,630.593475,1175174
4,3. html,HTML,9626374,813.6,0.008452,1408.435349,1145903

In [26]:
# CTR 
df['클릭률(%)'] = df['클릭수'] / df['노출수'] * 100

In [29]:
# CPC 
cpc = round(df['평균클릭비용(VAT포함,원)'], 0)
df['총비용(vat포함, 원)'] = cpc / df['클릭률(%)'] * 100

In [33]:
pd.set_option('display.float_format', '{:.2f}'.format) # 형식 float 형식으로

In [32]:
df.describe()

             노출수     클릭수  클릭률(%)  평균클릭비용(VAT포함,원)  총비용(VAT포함,원)  총비용(vat포함, 원)
count    1381.00 1381.00 1381.00          1381.00       1381.00        1057.00
mean    35054.15   52.53    0.35           981.63      37919.58     1852654.59
std    296465.03  387.50    1.00          1372.39     142149.16     3640207.22
min      1001.00    0.00    0.00             0.00          0.00        1206.01
25%      1814.00    1.20    0.01            64.17         77.00      170145.56
50%      3805.00    3.60    0.06           395.98       2123.00      555573.33
75%     10734.00   14.40    0.24          1302.81      17435.00     2089049.82
max   9626374.00 9606.00   13.59          9362.53    2512444.00    40606266.67

## 중점관리키워드 추출 
- 노출수, 클릭 수 기준 상위 5%에 해당하는 키워드 추출 
    - 95 백분위 수 찾기 (quantile 함수 사용)
    - 상위 5%에 해당하는 키워드 추출

In [35]:
imp = df['노출수']

In [36]:
# 95 백분위 수 찾기 
imp.quantile()

3805.0

In [37]:
imp.median()

3805.0

In [38]:
print(imp.quantile(0))
print(imp.min())

1001.0
1001

In [39]:
print(imp.quantile(1))
print(imp.max())

9626374.0
9626374

In [40]:
imp.quantile(0.95)

82858.0

In [42]:
imp = imp[imp >= imp.quantile(0.95)]
imp

0      2319456
4      9626374
9      1887822
173    3095998
Name: 노출수, dtype: int64

In [43]:
df_index = df.set_index('키워드')

In [44]:
df_index

,광고그룹,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)","총비용(vat포함, 원)"
키워드,,,,,,,
-,올인원 패키지 : 디자인 툴_파워컨텐츠_포토샵,2319456,9606.00,0.41,261.55,2512444,63262.28
-,올인원 패키지 : 업무자동화_VBA,767491,8058.00,1.05,295.97,2384965,28192.77
일러스트,ㅍAOP 전체_중복키워드_디자인(삭제),1137840,324.00,0.03,4841.66,1568699,17004386.67
-,올인원 패키지 : 데이터 분석 입문 온라인_파콘,694106,1863.60,0.27,630.59,1175174,235018.72
HTML,3. html,9626374,813.60,0.01,1408.44,1145903,16659211.64
...,...,...,...,...,...,...,...
엑셀셀서식,올인원 패키지 : 업무자동화_3. 엑셀,24016,0.00,0.00,0.00,0,nan
MATCH,올인원 패키지 : 업무자동화_3. 엑셀,32287,0.00,0.00,0.00,0,nan
LTV,마케팅KPI수립,32602,0.00,0.00,0.00,0,nan
DECISION,data_camp_rmp_8,60844,0.00,0.00,0.00,0,nan
REST,4. 웹의 동작,61193,0.00,0.00,0.00,0,nan

In [45]:
imp = df_index['노출수']
imp = imp[imp >=  imp.quantile(0.95)]

In [46]:
imp.head()

키워드
-       2319456
-        767491
일러스트    1137840
-        694106
HTML    9626374
Name: 노출수, dtype: int64

In [47]:
clk = df_index['클릭수']
clk = clk[clk >= clk.quantile(0.95)]

In [48]:
clk.head()

키워드
-      9606.00
-      8058.00
일러스트    324.00
-      1863.60
HTML    813.60
Name: 클릭수, dtype: float64

In [50]:
# 노출수와 클릭수 모두 95 백분위 수 이상인 키워드 
imp = df_index['노출수']
clk = df_index['클릭수']

In [54]:
result = df_index[(imp>=imp.quantile(0.95)) & (clk >= clk.quantile(0.95))]

In [55]:
result.head()

,광고그룹,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)","총비용(vat포함, 원)"
키워드,,,,,,,
-,올인원 패키지 : 디자인 툴_파워컨텐츠_포토샵,2319456,9606.00,0.41,261.55,2512444,63262.28
-,올인원 패키지 : 업무자동화_VBA,767491,8058.00,1.05,295.97,2384965,28192.77
일러스트,ㅍAOP 전체_중복키워드_디자인(삭제),1137840,324.00,0.03,4841.66,1568699,17004386.67
-,올인원 패키지 : 데이터 분석 입문 온라인_파콘,694106,1863.60,0.27,630.59,1175174,235018.72
HTML,3. html,9626374,813.60,0.01,1408.44,1145903,16659211.64

In [56]:
result.index

Index(['-', '-', '일러스트', '-', 'HTML', '파이썬', '코딩', 'C언어', '가상화폐', '포토샵',
       '블록체인', '엑셀', '-', '포토샵', '컴퓨터활용능력', '컴퓨터활용능력2급', '컴퓨터활용능력1급', '포토샵',
       '-', '프리미어프로', '폰트', '스케치', '포토샵', '글씨체', '한글폰트', '마블', '바이럴마케팅'],
      dtype='object', name='키워드')

## 노출수, 클릭수 기준 상위 5%의 키워드가 아닌데도 비용이 많이 쓰이는 키워드 
- 노출수 95 백분위수 미만
- 클릭수 95 백분위수 미만
- 총비용 85 백분위수 이상
- 총비용 95 백분위수 미만

In [57]:
cost = df_index['총비용(VAT포함,원)']

In [58]:
result = df_index[(imp < imp.quantile(0.95)) & (clk < clk.quantile(0.95)) & (cost >= cost.quantile(0.85))]
result

,광고그룹,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)","총비용(vat포함, 원)"
키워드,,,,,,,
파이썬교육,올인원 패키지 : 업무자동화_2. 파이썬,1226,56.40,4.60,8831.01,498069,191964.65
어플개발,1. 모바일앱개발_교육,8033,84.00,1.05,5427.85,455939,519084.81
UIUX디자인,올인원 패키지 : UX/UI 디자인 입문_연관검색어,9627,118.80,1.23,3684.91,437767,298615.28
앱개발,1. 모바일앱개발_교육,23962,103.20,0.43,3983.45,411092,924812.46
어플제작,1. 모바일앱개발_교육,6496,79.20,1.22,5185.00,410652,425274.75
...,...,...,...,...,...,...,...
엑셀셀서식,올인원 패키지 : 업무자동화_3. 엑셀,24016,0.00,0.00,0.00,0,nan
MATCH,올인원 패키지 : 업무자동화_3. 엑셀,32287,0.00,0.00,0.00,0,nan
LTV,마케팅KPI수립,32602,0.00,0.00,0.00,0,nan
DECISION,data_camp_rmp_8,60844,0.00,0.00,0.00,0,nan
REST,4. 웹의 동작,61193,0.00,0.00,0.00,0,nan

In [59]:
result.index

Index(['파이썬교육', '어플개발', 'UIUX디자인', '앱개발', '어플제작', '앱제작', '자바스크립트', '게임학원',
       '영상제작', 'SNS마케팅교육',
       ...
       '가상머신', '부동산책', 'VD', '포토샵단축키', 'SUMIF', '엑셀셀서식', 'MATCH', 'LTV',
       'DECISION', 'REST'],
      dtype='object', name='키워드', length=1268)

### 광고그룹 분석 
- as-is : 키워드 기준 분석 
    - 키워드의 노출 수 / 클릭 수 / 총 비용 .... 
- to-bo : 광고그룹 기준 분석 
    - 데이터의 구성을 광고그룹 기준으로 변경 
    - 광고그룹의 노출 수/ 클릭 수 / 총 비용...
    - groupby 함수 사용

In [60]:
grouped = df.groupby('광고그룹')

In [61]:
grouped.count()

,키워드,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)","총비용(vat포함, 원)"
광고그룹,,,,,,,
#000_마케팅 전체_main,48,48,48,48,48,48,36
001.BASIC DESIGN,9,9,9,9,9,9,7
001.데이터분석/ 통계,10,10,10,10,10,10,10
002.R,9,9,9,9,9,9,7
002.UX/UI,5,5,5,5,5,5,3
...,...,...,...,...,...,...,...
포토샵 유치원_일러스트레이터 유치원,13,13,13,13,13,13,10
프로그래밍 유치원,8,8,8,8,8,8,7
프로그래밍 전체,12,12,12,12,12,12,7
프로그래밍 전체_파워컨텐츠_블록체인(삭제),3,3,3,3,3,3,3
프론트엔드 개발 스쿨 12기_기존 키워드,1,1,1,1,1,1,1

In [62]:
grouped.mean()

,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)","총비용(vat포함, 원)"
광고그룹,,,,,,
#000_마케팅 전체_main,14780.15,8.40,0.18,625.09,7243.96,1295570.80
001.BASIC DESIGN,5738.56,6.80,0.23,298.69,2427.33,908546.23
001.데이터분석/ 통계,3715.00,20.28,0.89,1021.47,19575.60,804050.67
002.R,13413.78,8.53,0.11,360.04,4796.00,706103.49
002.UX/UI,3090.80,4.08,0.09,69.93,550.00,93635.24
...,...,...,...,...,...,...
포토샵 유치원_일러스트레이터 유치원,72092.69,16.71,0.05,648.33,15781.62,2491380.94
프로그래밍 유치원,5921.62,7.80,0.22,2032.33,23617.00,6235102.10
프로그래밍 전체,90375.00,9.20,0.02,123.88,1626.17,1150799.59
프로그래밍 전체_파워컨텐츠_블록체인(삭제),65353.33,2344.40,3.64,192.77,431159.67,5737.10
프론트엔드 개발 스쿨 12기_기존 키워드,2015.00,2.40,0.12,64.17,154.00,53733.33

In [63]:
grouped.median()

,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)","총비용(vat포함, 원)"
광고그룹,,,,,,
#000_마케팅 전체_main,2765.00,3.60,0.06,765.97,2458.50,696649.06
001.BASIC DESIGN,5524.00,2.40,0.04,357.50,1023.00,466830.00
001.데이터분석/ 통계,1813.00,13.80,0.57,1096.80,13464.00,188199.79
002.R,5184.00,3.60,0.03,119.17,1287.00,338773.33
002.UX/UI,2649.00,1.20,0.09,73.33,88.00,74825.00
...,...,...,...,...,...,...
포토샵 유치원_일러스트레이터 유치원,5763.00,3.60,0.02,852.50,2706.00,2391976.25
프로그래밍 유치원,3748.00,3.00,0.12,1763.82,8002.50,744064.58
프로그래밍 전체,3455.50,1.20,0.01,130.50,225.50,1420550.83
프로그래밍 전체_파워컨텐츠_블록체인(삭제),64981.00,2798.40,3.52,239.81,334961.00,6823.02
프론트엔드 개발 스쿨 12기_기존 키워드,2015.00,2.40,0.12,64.17,154.00,53733.33